version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: telecom_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-telecom_db}
      MYSQL_USER: ${MYSQL_USER:-telecom_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-telecom_password123}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - telecom_network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO

  # Django Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: telecom_backend
    restart: unless-stopped
    environment:
      - USE_MYSQL=true
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE:-telecom_db}
      - MYSQL_USER=${MYSQL_USER:-telecom_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-telecom_password123}
      - DEBUG=False
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/app
    networks:
      - telecom_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Frontend Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: telecom_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - telecom_network
    environment:
      - API_BASE_URL=http://backend:8000

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: telecom_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-telecom_user}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-telecom_password123}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword123}
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - telecom_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: telecom_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - telecom_network
    command: redis-server --appendonly yes

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: telecom_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - telecom_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  telecom_network:
    driver: bridge 