# Generated by Django 4.2.7 on 2025-06-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа оборудования (например, TP-Link TL-WR74)', max_length=255, verbose_name='Наименование типа оборудования')),
                ('serial_mask', models.CharField(help_text='Маска для валидации серийных номеров (например, XXAAAAAXAA)', max_length=50, verbose_name='Маска серийного номера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'equipment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Уникальный серийный номер оборудования', max_length=100, verbose_name='Серийный номер')),
                ('note', models.TextField(blank=True, help_text='Дополнительная информация об оборудовании', null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата мягкого удаления записи', null=True, verbose_name='Дата удаления')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment_type', 'serial_number'], name='equipment_equipme_324fad_idx'), models.Index(fields=['serial_number'], name='equipment_serial__ac559e_idx'), models.Index(fields=['deleted_at'], name='equipment_deleted_7cb4c2_idx')],
                'unique_together': {('equipment_type', 'serial_number')},
            },
        ),
    ]
